#!/bin/bash
# /etc/init.d/safehome

### BEGIN INIT INFO
# Provides:          safehome
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Safe home startup
# Description:       This service starts the Safe home server
### END INIT INFO


case "$1" in 
    start)
        echo "Starting safehome"
        /home/pi/Documents/apache-tomcat-8.5.15/bin/startup.sh
        ;;
    stop)
        echo "Stopping safehome"
        /home/pi/Documents/apache-tomcat-8.5.15/bin/shutdown.sh
        ;;
    *)
        echo "Usage: /etc/init.d/safehome start|stop"
        exit 1
        ;;
esac

exit 0
